# Generated by Django 4.2.17 on 2025-01-10 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_number', models.IntegerField(unique=True)),
                ('draw_date', models.DateField()),
                ('winning_numbers', models.CharField(max_length=50)),
                ('bonus_number', models.IntegerField()),
                ('total_sales', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tickets', models.IntegerField(default=0)),
                ('auto_tickets', models.IntegerField(default=0)),
                ('manual_tickets', models.IntegerField(default=0)),
                ('first_prize_winners', models.IntegerField(default=0)),
                ('second_prize_winners', models.IntegerField(default=0)),
                ('third_prize_winners', models.IntegerField(default=0)),
                ('fourth_prize_winners', models.IntegerField(default=0)),
                ('fifth_prize_winners', models.IntegerField(default=0)),
                ('draw_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lotto.drawresult')),
            ],
        ),
        migrations.CreateModel(
            name='LottoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(max_length=50)),
                ('ticket_type', models.CharField(choices=[('AUTO', '자동'), ('MANUAL', '수동')], max_length=6)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('draw_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', '활성'), ('CHECKED', '확인완료')], default='ACTIVE', max_length=7)),
                ('prize_rank', models.IntegerField(blank=True, null=True)),
                ('prize_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
